-- local status, jdtls = pcall(require, "jdtls")
-- if not status then
--   return
-- end
--
-- local capabilities = require("lvim.lsp").common_capabilities()
-- local extendedClientCapabilities = jdtls.extendedClientCapabilities
-- extendedClientCapabilities.resolveAdditionalTextEditsSupport = true
--
-- local home = os.getenv "HOME"
-- local mason_path = home .. "/.local/share/lvim/mason/"
-- local jdtls_dir = mason_path .. "packages/jdtls"
-- local config_dir = jdtls_dir .. '/config_linux'
-- local plugins_dir = jdtls_dir .. '/plugins/'
-- local path_to_jar = plugins_dir .. 'org.eclipse.equinox.launcher_1.7.0.v20250519-0528.jar'
-- local path_to_lombok = jdtls_dir .. '/lombok.jar'
--
-- local root_markers = { 'gradlew', '.git', 'mvnw', 'settings.gradle', 'pom.xml' }
-- local root_dir = require("jdtls.setup").find_root(root_markers)
-- if root_dir == "" then
--   return
-- end
--
-- local project_name = vim.fn.fnamemodify(vim.fn.getcwd(), ":p:h:t")
-- local workspace_dir = home .. '/.workspace/' .. project_name
-- os.execute("mkdir " .. workspace_dir)
--
-- local java = "/usr/lib/jvm/java-21-openjdk-amd64/bin/java"
--
-- lvim.builtin.dap.active = true
-- local bundles = {}
-- vim.list_extend(bundles, vim.split(vim.fn.glob(mason_path .. "packages/java-test/extension/server/*.jar"), "\n"))
-- vim.list_extend(
--   bundles,
--   vim.split(
--     vim.fn.glob(mason_path .. "packages/java-debug-adapter/extension/server/com.microsoft.java.debug.plugin-*.jar"),
--     "\n"
--   )
-- )
--
-- local config = {
--   cmd = {
--     java,
--     '-Declipse.application=org.eclipse.jdt.ls.core.id1',
--     '-Dosgi.bundles.defaultStartLevel=4',
--     '-Declipse.product=org.eclipse.jdt.ls.core.product',
--     '-Dlog.protocol=true',
--     '-Dlog.level=ALL',
--     '-Xmx1g',
--     '--add-modules=ALL-SYSTEM',
--     '--add-opens', 'java.base/java.util=ALL-UNNAMED',
--     '--add-opens', 'java.base/java.lang=ALL-UNNAMED',
--     '-javaagent:' .. path_to_lombok,
--     '-jar', path_to_jar,
--     '-configuration', config_dir,
--     '-data', workspace_dir
--   },
--
--   root_dir = root_dir,
--   capabilities = capabilities,
--   settings = {
--     java = {
--       eclipse = {
--         downloadSources = true,
--       },
--       configuration = {
--         updateBuildConfiguration = "interactive",
--         runtimes = {
--           -- {
--           --   name = "JavaSE-17",
--           --   path = sdkman_path .. "17.0.6-tem",
--           -- },
--           -- {
--           --   name = "JavaSE-18",
--           --   path = sdkman_path .. "18.0.1-tem",
--           -- },
--           -- {
--           --   name = "JavaSE-19",
--           --   path = sdkman_path .. "19.0.2-tem",
--           -- },
--           -- {
--           --   name = "JavaSE-20",
--           --   path = sdkman_path .. "20-tem",
--           -- },
--         },
--       },
--       gradle = {
--         enabled = true,
--       },
--       maven = {
--         downloadSources = true,
--       },
--       implementationsCodeLens = {
--         enabled = true,
--       },
--       referencesCodeLens = {
--         enabled = true,
--       },
--       references = {
--         includeDecompiledSources = true,
--       },
--       inlayHints = {
--           parameterNames = {
--               enabled = "all",
--           },
--       },
--       codeGeneration = {
--         toString = {
--           template = "${object.className}{${member.name()}=${member.value}, ${otherMembers}}"
--         },
--         hashCodeEquals = {
--           useJava7Objects = true,
--         },
--         useBlocks = true,
--       },
--     },
--     format = {
--     },
--   },
--   signatureHelp = { enabled = true },
--   extendedClientCapabilities = extendedClientCapabilities,
--   completion = {
--       favoriteStaticMembers = {
--         "org.junit.jupiter.api.Assertions.*",
--         "java.util.Objects.requireNonNull",
--         "java.util.Objects.requireNonNullElse",
--         "org.mockito.Mockito.*",
--         "org.springframework.*"
--       },
--       importOrder = {
--       "java",
--       "javax",
--       "com",
--       "org"
--     },
--   },
--   sources = {
--     organizeImports = {
--       starThreshold = 9999,
--       staticStarThreshold = 9999,
--     },
--   },
--   codeGeneration = {
--     toString = {
--       template = "${object.className}{${member.name()}=${member.value}, ${otherMembers}}",
--     },
--     useBlocks = true,
--   },
--   flags = {
--     allow_incremental_sync = true,
--   },
--   init_options = {
--     bundles = bundles,
--   },
-- }
--
-- require('jdtls').start_or_attach(config)
--
-- config["on_attach"] = function(client, bufnr)
--   local _, _ = pcall(vim.lsp.codelens.refresh)
--  require("jdtls").setup_dap({ hotcodereplace = "auto" })
--  require("lvim.lsp").on_attach(client, bufnr)
--   local status_ok, jdtls_dap = pcall(require, "jdtls.dap")
--   if status_ok then
--     jdtls_dap.setup_dap_main_class_configs()
--   end
-- end
--
-- vim.api.nvim_create_autocmd({ "BufWritePost" }, {
--   pattern = { "*.java" },
--   callback = function()
--     local _, _ = pcall(vim.lsp.codelens.refresh)
--   end,
-- })
--
-- local formatters = require "lvim.lsp.null-ls.formatters"
-- formatters.setup {
--   { command = "google_java_format", filetypes = { "java" } },
-- }
--
-- local status_ok, which_key = pcall(require, "which-key")
-- if not status_ok then
--   return
-- end
--
-- local opts = {
--   mode = "n",
--   prefix = "<leader>",
--   buffer = nil,
--   silent = true,
--   noremap = true,
--   nowait = true,
-- }
--
-- local vopts = {
--   mode = "v",
--   prefix = "<leader>",
--   buffer = nil,
--   silent = true,
--   noremap = true,
--   nowait = true,
-- }
--
-- local mappings = {
--   ca = {
--     "<Cmd>lua require('jdtls').code_action()<CR>", "Code Action",
--   },
--   rp = {
--     "<Cmd>lua vim.lsp.buf.rename()<CR>", "Rename Project",
--   },
-- }
--
-- local vmappings = {
--     v = { "<Esc><Cmd>lua require('jdtls').extract_variable(true)<CR>", "Extract Variable" },
--     c = { "<Esc><Cmd>lua require('jdtls').extract_constant(true)<CR>", "Extract Constant" },
--     m = { "<Esc><Cmd>lua require('jdtls').extract_method(true)<CR>", "Extract Method" },
-- }
--
-- which_key.register(mappings, opts)
-- which_key.register(vmappings, vopts)
-- which_key.register(vmappings, vopts)
